#Minecraft server properties
#Sat Aug 22 00:35:53 PDT 2026
accepts-transfers=false
allow-flight=false
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
chat-spam-threshold-seconds=10
command-spam-threshold-seconds=10
debug=false
difficulty=easy
enable-code-of-conduct=false
enable-command-block=true
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=UhWR8jrEvJjTtuTQZm9TvQXHepbfka0ozsu7JLLv
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=500
max-tick-time=60000
max-world-size=29999984
motd=YaPcore | Folia Game |Yap Edge
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=0
prevent-proxy-connections=false
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=http\://yapcoremc.yaplabs.us/pack/yapcore-default-155d5f4f.zip
resource-pack-id=28f8b35f-cec9-3029-9f79-3c86a1b0d20c
resource-pack-prompt={"text"\:"This server offers a resource pack (Faithful 64x + YaP Vehicles). Click Yes to download, or No to play without it."}
resource-pack-sha1=155d5f4f270975ac82390fecf4f7695e2c76d74e
server-ip=127.0.0.1
server-port=25567
simulation-distance=10
spawn-protection=0
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=10
white-list=false
