package com.yapcore.protocol.via.catalog;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.reflect.TypeToken;
import com.yapcore.protocol.java.ProtocolBand;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.EnumMap;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;

/**
 * Loads per-band item/block/entity catalogs from {@code protocol/catalogs/*.json}
 * (generated by {@code scripts/generate-protocol-catalogs.mjs} from minecraft-data).
 */
public final class CatalogStore {

    private static final Logger LOG = Logger.getLogger("YaPcore.Catalog");
    private static final Gson GSON = new Gson();
    private static final CatalogStore INSTANCE = new CatalogStore();

    public record BandCatalog(
            ProtocolBand band,
            String minecraftVersion,
            Integer protocol,
            String sectionFormat,
            Map<Integer, String> items,
            Map<String, Integer> itemsByName,
            Map<Integer, String> blocks,
            Map<String, Integer> blocksByName,
            Map<Integer, String> entities,
            Map<String, Integer> entitiesByName
    ) {
        public int itemToModern(int legacyId, BandCatalog modern) {
            String name = items.get(legacyId);
            if (name == null) {
                return legacyId;
            }
            return modern.itemsByName.getOrDefault(name, legacyId);
        }

        public int itemToLegacy(int modernId, BandCatalog modern) {
            String name = modern.items.get(modernId);
            if (name == null) {
                return modernId;
            }
            return itemsByName.getOrDefault(name, modernId);
        }

        public int blockToModern(int legacyId, BandCatalog modern) {
            String name = blocks.get(legacyId);
            if (name == null) {
                return modern.standInBlockState();
            }
            Integer mapped = modern.blocksByName.get(name);
            if (mapped != null) {
                return mapped;
            }
            return modern.standInBlockState();
        }

        public int blockToLegacy(int modernId, BandCatalog modern) {
            String name = modern.blocks.get(modernId);
            if (name == null) {
                return standInBlockState();
            }
            Integer mapped = blocksByName.get(name);
            if (mapped != null) {
                return mapped;
            }
            return standInBlockState();
        }

        public int entityToModern(int legacyType, BandCatalog modern) {
            String name = entities.get(legacyType);
            if (name == null) {
                return legacyType;
            }
            return modern.entitiesByName.getOrDefault(name, legacyType);
        }

        /**
         * Map a modern entity type onto this (older) catalog.
         * Unknown names → documented stand-in ({@code pig}, else {@code armor_stand}, else 0)
         * so mid clients never see a modern type id they cannot spawn.
         */
        public int entityToLegacy(int modernType, BandCatalog modern) {
            String name = modern.entities.get(modernType);
            if (name == null) {
                return standInEntityType();
            }
            Integer mapped = entitiesByName.get(name);
            if (mapped != null) {
                return mapped;
            }
            return standInEntityType();
        }

        /** VB.22 placeholder when the client catalog lacks the modern entity name. */
        public int standInEntityType() {
            Integer pig = entitiesByName.get("pig");
            if (pig != null) {
                return pig;
            }
            Integer stand = entitiesByName.get("armor_stand");
            if (stand != null) {
                return stand;
            }
            return 0;
        }

        /** VB.23 placeholder when the client catalog lacks the modern block name. */
        public int standInBlockState() {
            Integer stone = blocksByName.get("stone");
            if (stone != null) {
                return stone;
            }
            Integer air = blocksByName.get("air");
            if (air != null) {
                return air;
            }
            return 0;
        }
    }

    private final EnumMap<ProtocolBand, BandCatalog> bands = new EnumMap<>(ProtocolBand.class);
    private final boolean loaded;

    private CatalogStore() {
        boolean ok = true;
        for (ProtocolBand band : ProtocolBand.values()) {
            BandCatalog c = loadBand(band);
            if (c == null && band == ProtocolBand.V_FUTURE) {
                // 4.V1: future clients share modern catalog until dedicated dumps exist
                BandCatalog modern = loadBand(ProtocolBand.V26_2);
                if (modern != null) {
                    c = new BandCatalog(
                            ProtocolBand.V_FUTURE,
                            modern.minecraftVersion() + "+future",
                            modern.protocol(),
                            modern.sectionFormat(),
                            modern.items(),
                            modern.itemsByName(),
                            modern.blocks(),
                            modern.blocksByName(),
                            modern.entities(),
                            modern.entitiesByName()
                    );
                }
            }
            if (c != null) {
                bands.put(band, c);
            } else {
                ok = false;
                LOG.warning("Missing protocol catalog for " + band);
            }
        }
        this.loaded = ok && !bands.isEmpty();
        if (loaded) {
            BandCatalog modern = bands.get(ProtocolBand.V26_2);
            LOG.info("Protocol catalogs loaded: " + bands.size() + " bands"
                    + (modern != null ? (" modern items=" + modern.items.size()) : ""));
        }
    }

    public static CatalogStore get() {
        return INSTANCE;
    }

    public boolean isLoaded() {
        return loaded;
    }

    public BandCatalog band(ProtocolBand band) {
        BandCatalog c = bands.get(band);
        if (c == null && band == ProtocolBand.V_FUTURE) {
            return bands.get(ProtocolBand.V26_2);
        }
        return c;
    }

    public BandCatalog modern() {
        return bands.get(ProtocolBand.V26_2);
    }

    public int remapItem(ProtocolBand from, ProtocolBand to, int id) {
        BandCatalog a = bands.get(from);
        BandCatalog b = bands.get(to);
        if (a == null || b == null || from == to) {
            return id;
        }
        return a.itemToModern(id, b);
    }

    public int remapBlock(ProtocolBand from, ProtocolBand to, int id) {
        BandCatalog a = bands.get(from);
        BandCatalog b = bands.get(to);
        if (a == null || b == null || from == to) {
            return id;
        }
        return a.blockToModern(id, b);
    }

    public int remapEntity(ProtocolBand from, ProtocolBand to, int id) {
        BandCatalog a = bands.get(from);
        BandCatalog b = bands.get(to);
        if (a == null || b == null || from == to) {
            return id;
        }
        return a.entityToModern(id, b);
    }

    public String sectionFormat(ProtocolBand band) {
        BandCatalog c = bands.get(band);
        return c == null ? "paletted" : c.sectionFormat();
    }

    private static BandCatalog loadBand(ProtocolBand band) {
        String path = "protocol/catalogs/" + band.name() + ".json";
        try (InputStream in = CatalogStore.class.getClassLoader().getResourceAsStream(path)) {
            if (in == null) {
                return null;
            }
            JsonObject root = GSON.fromJson(new InputStreamReader(in, StandardCharsets.UTF_8), JsonObject.class);
            Map<String, String> itemsS = GSON.fromJson(root.get("items"), new TypeToken<Map<String, String>>(){}.getType());
            Map<String, Double> itemsByNameN = GSON.fromJson(root.get("itemsByName"), new TypeToken<Map<String, Double>>(){}.getType());
            Map<String, String> blocksS = GSON.fromJson(root.get("blocks"), new TypeToken<Map<String, String>>(){}.getType());
            Map<String, Double> blocksByNameN = GSON.fromJson(root.get("blocksByName"), new TypeToken<Map<String, Double>>(){}.getType());
            Map<String, String> entitiesS = GSON.fromJson(root.get("entities"), new TypeToken<Map<String, String>>(){}.getType());
            Map<String, Double> entitiesByNameN = GSON.fromJson(root.get("entitiesByName"), new TypeToken<Map<String, Double>>(){}.getType());
            String section = "paletted";
            if (root.has("chunk") && root.getAsJsonObject("chunk").has("sectionFormat")) {
                section = root.getAsJsonObject("chunk").get("sectionFormat").getAsString();
            }
            Integer protocol = root.has("protocol") && !root.get("protocol").isJsonNull()
                    ? root.get("protocol").getAsInt() : null;
            return new BandCatalog(
                    band,
                    root.has("minecraftVersion") ? root.get("minecraftVersion").getAsString() : "?",
                    protocol,
                    section,
                    toIntStringMap(itemsS),
                    toNameIntMap(itemsByNameN),
                    toIntStringMap(blocksS),
                    toNameIntMap(blocksByNameN),
                    toIntStringMap(entitiesS),
                    toNameIntMap(entitiesByNameN)
            );
        } catch (Exception e) {
            LOG.warning("Failed loading " + path + ": " + e.getMessage());
            return null;
        }
    }

    private static Map<Integer, String> toIntStringMap(Map<String, String> in) {
        if (in == null) {
            return Map.of();
        }
        Map<Integer, String> out = new HashMap<>(in.size());
        for (var e : in.entrySet()) {
            try {
                out.put(Integer.parseInt(e.getKey()), e.getValue());
            } catch (NumberFormatException ignored) {
                // skip
            }
        }
        return Collections.unmodifiableMap(out);
    }

    private static Map<String, Integer> toNameIntMap(Map<String, Double> in) {
        if (in == null) {
            return Map.of();
        }
        Map<String, Integer> out = new HashMap<>(in.size());
        for (var e : in.entrySet()) {
            out.put(e.getKey(), e.getValue().intValue());
        }
        return Collections.unmodifiableMap(out);
    }
}
