package org.bukkit;

/** Paper API stub (YaPcore compatibility). */
public enum Effect {
    CLICK2, CLICK1, BOW_FIRE, DOOR_TOGGLE, IRON_DOOR_TOGGLE, TRAPDOOR_TOGGLE, IRON_TRAPDOOR_TOGGLE, FENCE_GATE_TOGGLE, DOOR_CLOSE, IRON_DOOR_CLOSE, TRAPDOOR_CLOSE, IRON_TRAPDOOR_CLOSE, FENCE_GATE_CLOSE, EXTINGUISH;
}
