package org.bukkit;

/** Common materials for plugins / GUI / world APIs (expanding toward full catalog). */
public enum Material {
    AIR, STONE, GRANITE, DIORITE, ANDESITE, DIRT, GRASS_BLOCK, COARSE_DIRT, PODZOL, MYCELIUM,
    COBBLESTONE, OAK_PLANKS, SPRUCE_PLANKS, BIRCH_PLANKS, JUNGLE_PLANKS, ACACIA_PLANKS, DARK_OAK_PLANKS,
    BEDROCK, SAND, RED_SAND, GRAVEL, GOLD_ORE, IRON_ORE, COAL_ORE, LAPIS_ORE, DIAMOND_ORE, EMERALD_ORE,
    NETHER_QUARTZ_ORE, ANCIENT_DEBRIS, OAK_LOG, SPRUCE_LOG, BIRCH_LOG, JUNGLE_LOG, ACACIA_LOG, DARK_OAK_LOG,
    OAK_LEAVES, GLASS, WHITE_WOOL, ORANGE_WOOL, MAGENTA_WOOL, LIGHT_BLUE_WOOL, YELLOW_WOOL, LIME_WOOL,
    PINK_WOOL, GRAY_WOOL, LIGHT_GRAY_WOOL, CYAN_WOOL, PURPLE_WOOL, BLUE_WOOL, BROWN_WOOL, GREEN_WOOL,
    RED_WOOL, BLACK_WOOL, GOLD_BLOCK, IRON_BLOCK, DIAMOND_BLOCK, EMERALD_BLOCK, LAPIS_BLOCK, COAL_BLOCK,
    NETHERITE_BLOCK, BOOKSHELF, OBSIDIAN, TORCH, CHEST, ENDER_CHEST, CRAFTING_TABLE, FURNACE, LADDER,
    RAIL, POWERED_RAIL, DETECTOR_RAIL, LEVER, STONE_BUTTON, OAK_BUTTON, REDSTONE, REDSTONE_TORCH,
    REDSTONE_BLOCK, HOPPER, DROPPER, DISPENSER, NOTE_BLOCK, JUKEBOX, ENCHANTING_TABLE, ANVIL,
    CHIPPED_ANVIL, DAMAGED_ANVIL, BEACON, BARRIER, STRUCTURE_VOID, COMMAND_BLOCK, SPAWNER,
    WATER, LAVA, ICE, PACKED_ICE, BLUE_ICE, SNOW_BLOCK, CLAY, NETHERRACK, SOUL_SAND, SOUL_SOIL,
    GLOWSTONE, NETHER_BRICKS, END_STONE, PURPUR_BLOCK, QUARTZ_BLOCK, TERRACOTTA, WHITE_CONCRETE,
    ORANGE_CONCRETE, MAGENTA_CONCRETE, LIGHT_BLUE_CONCRETE, YELLOW_CONCRETE, LIME_CONCRETE,
    GRAY_STAINED_GLASS_PANE, LIME_STAINED_GLASS_PANE, BLACK_STAINED_GLASS_PANE, WHITE_STAINED_GLASS_PANE,
    OAK_SIGN, OAK_DOOR, IRON_DOOR, OAK_TRAPDOOR, IRON_TRAPDOOR, OAK_FENCE, OAK_FENCE_GATE,
    COBBLESTONE_WALL, STONE_BRICKS, MOSSY_STONE_BRICKS, CRACKED_STONE_BRICKS, BRICKS,
    SANDSTONE, RED_SANDSTONE, PRISMARINE, DARK_PRISMARINE, SEA_LANTERN, SHULKER_BOX, WHITE_SHULKER_BOX,
    // Items
    STICK, BOWL, STRING, FEATHER, GUNPOWDER, WHEAT_SEEDS, WHEAT, BREAD, FLINT, PORKCHOP, COOKED_PORKCHOP,
    APPLE, GOLDEN_APPLE, ENCHANTED_GOLDEN_APPLE, COAL, CHARCOAL, DIAMOND, IRON_INGOT, GOLD_INGOT,
    NETHERITE_INGOT, EMERALD, LAPIS_LAZULI, QUARTZ, AMETHYST_SHARD, COPPER_INGOT, RAW_IRON, RAW_GOLD,
    WOODEN_SWORD, STONE_SWORD, IRON_SWORD, GOLDEN_SWORD, DIAMOND_SWORD, NETHERITE_SWORD,
    WOODEN_PICKAXE, STONE_PICKAXE, IRON_PICKAXE, GOLDEN_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE,
    WOODEN_AXE, STONE_AXE, IRON_AXE, GOLDEN_AXE, DIAMOND_AXE, NETHERITE_AXE,
    WOODEN_SHOVEL, STONE_SHOVEL, IRON_SHOVEL, GOLDEN_SHOVEL, DIAMOND_SHOVEL, NETHERITE_SHOVEL,
    WOODEN_HOE, STONE_HOE, IRON_HOE, GOLDEN_HOE, DIAMOND_HOE, NETHERITE_HOE,
    BOW, ARROW, SPECTRAL_ARROW, TIPPED_ARROW, CROSSBOW, TRIDENT, SHIELD, TOTEM_OF_UNDYING,
    LEATHER_HELMET, LEATHER_CHESTPLATE, LEATHER_LEGGINGS, LEATHER_BOOTS,
    IRON_HELMET, IRON_CHESTPLATE, IRON_LEGGINGS, IRON_BOOTS,
    DIAMOND_HELMET, DIAMOND_CHESTPLATE, DIAMOND_LEGGINGS, DIAMOND_BOOTS,
    NETHERITE_HELMET, NETHERITE_CHESTPLATE, NETHERITE_LEGGINGS, NETHERITE_BOOTS,
    TURTLE_HELMET, ELYTRA, SADDLE, NAME_TAG, LEAD, PAPER, BOOK, WRITABLE_BOOK, WRITTEN_BOOK,
    MAP, FILLED_MAP, COMPASS, CLOCK, FISHING_ROD, CARROT_ON_A_STICK, WARPED_FUNGUS_ON_A_STICK,
    BUCKET, WATER_BUCKET, LAVA_BUCKET, MILK_BUCKET, POWDER_SNOW_BUCKET, AXOLOTL_BUCKET,
    SNOWBALL, EGG, ENDER_PEARL, ENDER_EYE, EXPERIENCE_BOTTLE, FIRE_CHARGE, WRITABLE_BOOK_ALT,
    PLAYER_HEAD, ZOMBIE_HEAD, CREEPER_HEAD, DRAGON_HEAD, SKELETON_SKULL, WITHER_SKELETON_SKULL,
    POTION, SPLASH_POTION, LINGERING_POTION, GLASS_BOTTLE, DRAGON_BREATH,
    OAK_BOAT, SPRUCE_BOAT, BIRCH_BOAT, JUNGLE_BOAT, ACACIA_BOAT, DARK_OAK_BOAT,
    MINECART, CHEST_MINECART, FURNACE_MINECART, TNT_MINECART, HOPPER_MINECART,
    MUSIC_DISC_13, MUSIC_DISC_CAT, MUSIC_DISC_BLOCKS, MUSIC_DISC_CHIRP, MUSIC_DISC_FAR,
    GOAT_HORN, BRUSH, SPYGLASS, RECOVERY_COMPASS, ECHO_SHARD;

    public boolean isAir() {
        return this == AIR;
    }

    public boolean isBlock() {
        return ordinal() < STICK.ordinal();
    }

    public boolean isItem() {
        return !isAir();
    }

    public static Material matchMaterial(String name) {
        if (name == null) {
            return null;
        }
        try {
            return Material.valueOf(name.trim().toUpperCase().replace(' ', '_'));
        } catch (IllegalArgumentException e) {
            return null;
        }
    }
}
