package org.bukkit;

/** Common sounds for plugin playSound APIs. */
public enum Sound {
    UI_BUTTON_CLICK,
    ENTITY_PLAYER_LEVELUP,
    ENTITY_EXPERIENCE_ORB_PICKUP,
    ENTITY_ITEM_PICKUP,
    BLOCK_NOTE_BLOCK_PLING,
    BLOCK_CHEST_OPEN,
    BLOCK_CHEST_CLOSE,
    ENTITY_VILLAGER_YES,
    ENTITY_VILLAGER_NO,
    ENTITY_ENDERMAN_TELEPORT,
    BLOCK_ANVIL_USE,
    ENTITY_GENERIC_EXPLODE,
    MUSIC_DISC_CAT,
    WEATHER_RAIN,
    BLOCK_PORTAL_TRAVEL
}
