worlds:
  allow-load: true
  allow-unload: true

selection:
  enabled: true
  max-volume: 1000000

schematics:
  enabled: true
  folder: schematics

brush:
  max-radius: 16

undo:
  max-sessions: 10

editor:
  enabled: true
  port: 8092
  bind: "0.0.0.0"
  # Hostname/IP players use in the browser (set to your server address)
  public-host: "127.0.0.1"

server-id: lobby
