package org.bukkit.event.inventory;

/** Paper API stub (YaPcore compatibility). */
public enum InventoryType {
    CHEST, DISPENSER, DROPPER, FURNACE, WORKBENCH, CRAFTING, ENCHANTING, BREWING, PLAYER, CREATIVE, MERCHANT, ENDER_CHEST, ANVIL, SMITHING, BEACON, HOPPER, SHULKER_BOX, BARREL, BLAST_FURNACE, LECTERN, SMOKER, LOOM, CARTOGRAPHY, GRINDSTONE, STONECUTTER, COMPOSTER, CHISELED_BOOKSHELF, JUKEBOX, DECORATED_POT, CRAFTER;
}
