#!/usr/bin/env python3
"""Generate 200+ YaP ability YAML packs for yap-abilities."""
from __future__ import annotations

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "yap-first-party/gameplay/abilities-plugin/src/main/resources/abilities"

ELEMENTS = [
    ("wind", "CLOUD", "ENTITY_BREEZE_WIND_CHARGE_BURST", "FEATHER"),
    ("water", "DRIPPING_WATER", "ENTITY_PLAYER_SPLASH", "PRISMARINE_SHARD"),
    ("earth", "BLOCK_CRACK", "BLOCK_STONE_BREAK", "COBBLESTONE"),
    ("fire", "FLAME", "ENTITY_BLAZE_SHOOT", "BLAZE_POWDER"),
]

TIERS = [
    ("strike", 1, 4, 12, "SNOWBALL", 1.2),
    ("bolt", 15, 10, 28, "ARROW", 1.6),
    ("blast", 30, 16, 42, "FIREBALL", 1.3),
    ("wave", 45, 22, 55, "DRAGON_FIREBALL", 1.1),
    ("surge", 60, 28, 68, "SMALL_FIREBALL", 1.4),
    ("storm", 75, 34, 80, "WITHER_SKULL", 1.5),
]

MELEE_STYLES = [
    ("slash", "SWEEP_ATTACK", "ENTITY_PLAYER_ATTACK_SWEEP"),
    ("cleave", "CRIT", "ENTITY_PLAYER_ATTACK_CRIT"),
    ("bash", "EXPLOSION", "ENTITY_IRON_GOLEM_ATTACK"),
    ("riposte", "ENCHANTED_HIT", "ENTITY_PLAYER_ATTACK_KNOCKBACK"),
    ("whirlwind", "CLOUD", "ENTITY_ENDER_DRAGON_FLAP"),
]

RANGED_STYLES = [
    ("shot", "CRIT", "ENTITY_ARROW_SHOOT"),
    ("volley", "FIREWORK", "ENTITY_FIREWORK_ROCKET_LAUNCH"),
    ("pierce", "CRIT", "ENTITY_ARROW_HIT"),
    ("bind", "SPELL_WITCH", "ENTITY_VEX_CHARGE"),
    ("barrage", "SMOKE", "ENTITY_SKELETON_SHOOT"),
]

PRAYER_BUFFS = [
    ("thick_skin", "defence", 5),
    ("burst_of_strength", "strength", 8),
    ("clarity", "attack", 8),
    ("sharp_eye", "ranged", 8),
    ("mystic_might", "magic", 8),
    ("protect_melee", "defence", 12),
    ("protect_missiles", "defence", 12),
    ("protect_magic", "defence", 12),
    ("retribution", "strength", 15),
    ("redemption", "defence", 20),
    ("smite", "strength", 25),
    ("chivalry", "attack", 30),
    ("piety", "defence", 35),
    ("rigour", "ranged", 40),
    ("augury", "magic", 45),
]


def yaml_header() -> str:
    return "# Generated by scripts/generate-ability-pack.py — do not hand-edit at scale\n"


def ability_block(
    aid: str,
    name: str,
    category: str,
    skill: str,
    level: int,
    prayer: int,
    max_hit: int,
    xp: int,
    particle: str,
    sound: str,
    rune: str,
    entity: str,
    speed: float,
    style: str = "magic",
    target_filter: str = "",
    cooldown: int = 0,
    debuff: str = "",
) -> str:
    lines = [
        f"  {aid}:",
        f'    name: "{name}"',
        f"    category: {category}",
        f"    min-level:",
        f"      {skill}: {level}",
        f"    costs:",
        f"      prayer: {prayer}",
        f"      runes:",
        f"        LAPIS_LAZULI: {max(1, level // 10 + 1)}",
    ]
    if rune:
        lines.append(f"        {rune}: 1")
    lines.extend([
        f"    cooldown: {cooldown}",
        f"    range: 20",
        f"    target: raycast",
    ])
    if target_filter:
        lines.append(f'    target-filter: {target_filter}')
    lines.extend([
        "    cast:",
        "      - type: vfx",
        f"        particle: {particle}",
        "        count: 10",
        "      - type: sound",
        f"        sound: {sound}",
        "        volume: 0.9",
        "      - type: xp",
        f"        skill: {skill}",
        f"        amount: {xp}",
        "        on-cast: true",
        "    projectile:",
        f"      entity: {entity}",
        f"      speed: {speed}",
        "      max-ticks: 45",
        "      trail:",
        f"        particle: {particle}",
        "        count: 3",
        "        interval: 2",
        "    on-hit:",
        "      - type: damage",
        f"        style: {style}",
        f"        max-hit: {max_hit}",
        "      - type: vfx",
        "        particle: EXPLOSION",
        "        count: 6",
        "      - type: knockback",
        "        power: 0.25",
    ])
    if debuff:
        lines.extend([
            "      - type: debuff",
            f"        id: {debuff}",
            "        stacks: 1",
        ])
    return "\n".join(lines) + "\n"


def gen_magic() -> dict[str, str]:
    packs: dict[str, list[str]] = {}
    for element, particle, sound, rune in ELEMENTS:
        bucket = f"magic_{element}.yml"
        packs.setdefault(bucket, [])
        for tier, base_level, max_hit, xp, entity, speed in TIERS:
            aid = f"{element}_{tier}"
            level = base_level + ELEMENTS.index((element, particle, sound, rune)) * 2
            name = f"{element.title()} {tier.title()}"
            packs[bucket].append(
                ability_block(
                    aid, name, "magic", "magic", level,
                    max(1, level // 8), max_hit, xp, particle, sound, rune, entity, speed,
                )
            )
    return {k: yaml_header() + "abilities:\n" + "".join(v) for k, v in packs.items()}


def gen_melee() -> str:
    chunks = []
    idx = 0
    for style, particle, sound in MELEE_STYLES:
        for tier in range(1, 11):
            idx += 1
            level = 5 + tier * 6 + idx // 3
            aid = f"melee_{style}_{tier}"
            name = f"{style.title()} {tier}"
            chunks.append(
                ability_block(
                    aid, name, "melee", "attack", level,
                    0, 3 + tier * 2, 8 + tier * 3, particle, sound, "",
                    "EGG", 1.0, style="melee", cooldown=15 + tier * 2,
                )
            )
    return yaml_header() + "abilities:\n" + "".join(chunks)


def gen_ranged() -> str:
    chunks = []
    idx = 0
    for style, particle, sound in RANGED_STYLES:
        for tier in range(1, 11):
            idx += 1
            level = 5 + tier * 6 + idx // 3
            aid = f"ranged_{style}_{tier}"
            name = f"{style.title()} {tier}"
            chunks.append(
                ability_block(
                    aid, name, "ranged", "ranged", level,
                    0, 3 + tier * 2, 8 + tier * 3, particle, sound, "ARROW",
                    "ARROW", 2.0, style="ranged", cooldown=10 + tier,
                )
            )
    return yaml_header() + "abilities:\n" + "".join(chunks)


def gen_prayer() -> str:
    chunks = []
    for idx, (aid, stat, level) in enumerate(PRAYER_BUFFS):
        chunks.append(
            f"  {aid}:\n"
            f'    name: "{aid.replace("_", " ").title()}"\n'
            f"    category: prayer\n"
            f"    min-level:\n"
            f"      prayer: {level}\n"
            f"    costs:\n"
            f"      prayer: {max(1, level // 5)}\n"
            f"    cooldown: 40\n"
            f"    target: self\n"
            f"    cast:\n"
            f"      - type: vfx\n"
            f"        particle: ENCHANT\n"
            f"        count: 20\n"
            f"      - type: sound\n"
            f"        sound: BLOCK_ENCHANTMENT_TABLE_USE\n"
            f"      - type: buff\n"
            f"        id: {aid}\n"
            f"        stacks: 1\n"
            f"      - type: xp\n"
            f"        skill: prayer\n"
            f"        amount: {5 + idx}\n"
            f"        on-cast: true\n"
        )
    return yaml_header() + "abilities:\n" + "".join(chunks)


def gen_utility() -> str:
    chunks = []
    for i in range(1, 25):
        aid = f"utility_phase_{i}"
        chunks.append(
            f"  {aid}:\n"
            f'    name: "Phase Step {i}"\n'
            f"    category: utility\n"
            f"    min-level:\n"
            f"      magic: {10 + i * 3}\n"
            f"    costs:\n"
            f"      prayer: {max(1, i // 2)}\n"
            f"    cooldown: {20 + i}\n"
            f"    target: self\n"
            f"    cast:\n"
            f"      - type: vfx\n"
            f"        particle: PORTAL\n"
            f"        count: 24\n"
            f"      - type: teleport\n"
            f"        distance: {4 + i // 2}\n"
            f"      - type: xp\n"
            f"        skill: magic\n"
            f"        amount: {10 + i}\n"
            f"        on-cast: true\n"
        )
    return yaml_header() + "abilities:\n" + "".join(chunks)


def gen_legacy() -> str:
    return yaml_header() + "abilities:\n" + "".join([
        ability_block("wind_strike", "Wind Strike", "magic", "magic", 1, 1, 4, 12,
                      "CLOUD", "ENTITY_BREEZE_WIND_CHARGE_BURST", "FEATHER", "SNOWBALL", 1.2),
        ability_block("water_strike", "Water Strike", "magic", "magic", 5, 2, 6, 18,
                      "DRIPPING_WATER", "ENTITY_PLAYER_SPLASH", "PRISMARINE_SHARD", "SNOWBALL", 1.2),
        ability_block("fire_bolt", "Fire Bolt", "magic", "magic", 15, 3, 10, 28,
                      "FLAME", "ENTITY_BLAZE_SHOOT", "BLAZE_POWDER", "FIREBALL", 1.4),
        ability_block("crumble", "Crumble Undead", "magic", "magic", 25, 4, 14, 35,
                      "SMOKE", "ENTITY_WITHER_SHOOT", "BONE", "WITHER_SKULL", 1.3,
                      target_filter="undead"),
    ])


def gen_curses() -> str:
    chunks = []
    for i in range(1, 31):
        aid = f"curse_{i:02d}"
        chunks.append(
            ability_block(
                aid, f"Curse {i}", "magic", "magic", 20 + i,
                max(1, i // 4), 5 + i // 2, 15 + i, "SPELL_WITCH", "ENTITY_EVOKER_CAST_SPELL",
                "FERMENTED_SPIDER_EYE", "EGG", 1.0, debuff="poison" if i % 2 == 0 else "slow",
            )
        )
    return yaml_header() + "abilities:\n" + "".join(chunks)


def gen_arcanum() -> str:
    chunks = []
    particles = ["ENCHANT", "END_ROD", "SOUL_FIRE_FLAME", "WITCH", "DRAGON_BREATH", "TOTEM"]
    for i in range(1, 31):
        p = particles[i % len(particles)]
        aid = f"arcanum_{i:02d}"
        chunks.append(
            ability_block(
                aid, f"Arcanum {i}", "magic", "magic", 40 + i * 2,
                max(2, i // 3), 8 + i // 2, 20 + i, p, "ENTITY_ILLUSIONER_CAST_SPELL",
                "GLOWSTONE_DUST", "FIREBALL", 1.25, debuff="burn" if i % 3 == 0 else "",
            )
        )
    return yaml_header() + "abilities:\n" + "".join(chunks)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    total = 0
    files: dict[str, str] = {}
    files.update(gen_magic())
    files["melee_specials.yml"] = gen_melee()
    files["ranged_specials.yml"] = gen_ranged()
    files["prayer_powers.yml"] = gen_prayer()
    files["utility.yml"] = gen_utility()
    files["legacy_spells.yml"] = gen_legacy()
    files["curses.yml"] = gen_curses()
    files["arcanum.yml"] = gen_arcanum()

    for name, content in sorted(files.items()):
        path = OUT / name
        path.write_text(content, encoding="utf-8")
        count = content.count("\n  ") - content.count("\n    ")
        # rough count via id lines
        count = sum(1 for line in content.splitlines() if line.startswith("  ") and line.endswith(":") and not line.startswith("    "))
        total += count
        print(f"wrote {path.name}: ~{count} abilities")

    print(f"TOTAL abilities: {total}")


if __name__ == "__main__":
    main()
