name: YaPLib
version: '0.0.0.2'
main: com.yapcore.lib.YapLibPlugin
api-version: '1.21'
folia-supported: true
load: STARTUP
author: YapLabs
description: Folia-safe packet intercept (ProtocolLib-class)
website: https://github.com/yaplabs
commands:
  yaplib:
    description: YaPLib admin
    usage: /yaplib status|reload
    permission: yaplib.admin
    aliases: [protocolib, protocollib]
permissions:
  yaplib.admin:
    default: op
